export const routeUrl = {
  dashboard: '/dashboard',
  draftPick: '/draftpick',
  tradeAnalysis: '/trade-analysis',
  draftBoard: '/draftboard',
  draftComparison: '/draft-comparison',
  updateLadder: '/update-ladder',
  projectList: '/project-list',
  scenarioPlanning: '/scenario-planning',
  smartList: '/smartlist',
  tradeOffer: '/trade-offer',
  listProjection: '/list-projection',
  tpp: '/tpp',
  contractStatus: '/contract-status',
  playerDatabase: '/player-database',
  playerReports: '/player-reports',
  playerHome: '/player-home',
  organisation: '/organisation',
  playerManager: '/player-manager',
  playerHomeInfo: '/player-home/:playerId',
  playerRanking: '/player-ranking',
  playerProfile: '/player-profile',
};
